# Generated by Django 4.1.10 on 2023-09-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0002_alter_material_created_by_alter_question_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="faculty",
        ),
    ]
