# Generated by Django 4.1.10 on 2023-09-21 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_manager", "0003_remove_subject_faculty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="course",
        ),
        migrations.AddField(
            model_name="subject",
            name="courses",
            field=models.ManyToManyField(
                null=True, related_name="subjects", to="course_manager.course"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                null=True, related_name="courses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
