# Generated by Django 4.1.10 on 2023-09-21 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_manager", "0004_remove_subject_course_subject_courses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                related_name="courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="courses",
            field=models.ManyToManyField(
                related_name="subjects", to="course_manager.course"
            ),
        ),
    ]
