# Generated by Django 4.1.10 on 2023-09-22 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0005_alter_course_students_alter_subject_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="courses",
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(default="Option", max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CourseSubjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_manager.course",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_manager.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="course_subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="course_manager.coursesubjects",
            ),
            preserve_default=False,
        ),
    ]
