# Generated by Django 4.1.10 on 2023-09-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_manager",
            "0006_remove_question_subject_remove_subject_courses_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("Option", "Option")], default="Option", max_length=10
            ),
        ),
    ]
