# Generated by Django 4.1.10 on 2023-10-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0010_alter_coursesubjects_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseenrollment",
            name="subscription_type",
            field=models.CharField(
                choices=[("FREE", "Free"), ("PAID", "Paid")],
                default="FREE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("OPTION", "Option")], default="OPTION", max_length=10
            ),
        ),
    ]
