# Generated by Django 4.1.10 on 2023-11-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0011_alter_courseenrollment_subscription_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
