# Generated by Django 4.1.10 on 2023-11-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0012_alter_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
