# Generated by Django 4.1.10 on 2023-11-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0013_alter_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
