# Generated by Django 4.1.10 on 2023-11-15 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0014_subject_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="material",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="material",
            name="type",
        ),
        migrations.RemoveField(
            model_name="material",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="material",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="material",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="study_materials/"),
        ),
        migrations.AddField(
            model_name="material",
            name="material_type",
            field=models.CharField(
                choices=[("PDF", "Pdf"), ("VIDEO", "Video"), ("FILE", "File")],
                default="PDF",
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="material",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="material",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="access_type",
            field=models.CharField(
                choices=[("FREE", "Free"), ("PAID", "Paid")],
                default="FREE",
                max_length=4,
            ),
        ),
    ]
