# Generated by Django 4.1.10 on 2023-11-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0017_remove_material_file_material_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
