# Generated by Django 4.1.10 on 2023-11-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0019_material_uploaded_file_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["id"]},
        ),
    ]
