# Generated by Django 4.1.10 on 2023-11-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0020_alter_course_options_alter_material_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="has_suggestion",
            field=models.BooleanField(default=False),
        ),
    ]
