# Generated by Django 4.1.10 on 2023-11-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0021_question_has_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("VE", "Very Easy"),
                    ("E", "Easy"),
                    ("M", "Moderate"),
                    ("H", "Hard"),
                    ("VH", "Very Hard"),
                ],
                default="M",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="test_type",
            field=models.CharField(
                choices=[("FLT", "Full Length Test"), ("SPT", "Self Practice Test")],
                default="FLT",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("SC", "Single Choice"), ("MC", "Multi Choice")],
                default="SC",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "course_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="course_manager.coursesubjects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="course_manager.topic",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "topic")},
            },
        ),
        migrations.AddField(
            model_name="question",
            name="sub_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course_manager.subtopic",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course_manager.topic",
            ),
        ),
    ]
