# Generated by Django 4.1.10 on 2023-11-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0023_alter_topic_name_alter_topic_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Very Easy", "Very Easy"),
                    ("Easy", "Easy"),
                    ("Moderate", "Moderate"),
                    ("Hard", "Hard"),
                    ("Very Hard", "Very Hard"),
                ],
                default="Moderate",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("Full Length Test", "Full Length Test"),
                    ("Self Practice Test", "Self Practice Test"),
                ],
                default="Full Length Test",
                max_length=20,
            ),
        ),
    ]
