# Generated by Django 4.1.10 on 2024-01-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0026_alter_material_material_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="reading_comprehension_passage",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "Single Choice"),
                    ("MULTI_CHOICE", "Multi Choice"),
                    ("FILL_IN_BLANKS", "Fill in the Blanks"),
                    ("READING_COMPREHENSION", "Reading Comprehension"),
                ],
                default="SINGLE_CHOICE",
                max_length=30,
            ),
        ),
    ]
