# Generated by Django 4.1.10 on 2024-02-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0027_question_reading_comprehension_passage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="question",
            name="show_calculator",
            field=models.BooleanField(default=False),
        ),
    ]
