# Generated by Django 4.1.10 on 2024-05-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0028_alter_question_options_question_show_calculator"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesubjects",
            name="correct_answer_marks",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="coursesubjects",
            name="incorrect_answer_marks",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
