# Generated by Django 4.1.10 on 2024-06-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0030_combinedscore_sectionscore"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SectionScore",
        ),
        migrations.AddField(
            model_name="combinedscore",
            name="subject_name",
            field=models.CharField(default="Math", max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
