# Generated by Django 4.1.10 on 2024-06-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0031_delete_sectionscore_combinedscore_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combinedscore",
            name="subject_name",
            field=models.CharField(max_length=30),
        ),
    ]
