# Generated by Django 4.1.10 on 2023-09-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0002_rename_type_test_test_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="section",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="section",
            name="no_of_questions",
        ),
        migrations.AddField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="test",
            name="format_type",
            field=models.CharField(
                choices=[
                    ("LINEAR", "Linear"),
                    ("DYNAMIC", "Dynamic"),
                    ("FLAT", "Flat"),
                ],
                default="LINEAR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("PRACTICE", "Practice"),
                    ("EXAM", "Exam"),
                    ("ASSIGNMENT", "Assignment"),
                ],
                default="EXAM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="testsubmission",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testsubmission",
            name="status",
            field=models.CharField(
                choices=[("YET_TO_START", "Yet to start"), ("COMPLETED", "Completed")],
                default="YET_TO_START",
                max_length=20,
            ),
        ),
    ]
