# Generated by Django 4.1.10 on 2023-09-30 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0008_remove_course_students_courseenrollment"),
        ("test_manager", "0003_alter_section_options_remove_section_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="subject",
        ),
        migrations.AddField(
            model_name="section",
            name="course_subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="course_manager.coursesubjects",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="section",
            name="sub_sections",
            field=models.JSONField(default=list),
        ),
    ]
