# Generated by Django 4.1.10 on 2023-10-01 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_manager",
            "0005_remove_testsubmission_result_result_test_submission_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testsubmission",
            name="expiration_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
