# Generated by Django 4.1.10 on 2023-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0007_alter_testsubmission_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("YET_TO_START", "Yet to start"),
                    ("IN_PROGRESS", "In progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="YET_TO_START",
                max_length=20,
            ),
        ),
    ]
