# Generated by Django 4.1.10 on 2023-11-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0009_alter_result_time_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
