# Generated by Django 4.1.10 on 2023-11-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0010_test_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="testsubmission",
            options={"ordering": ["id"]},
        ),
    ]
