# Generated by Django 4.1.10 on 2023-12-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0013_alter_testsubmission_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsubmission",
            name="selected_question_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of question IDs already selected for this test submission.",
            ),
        ),
    ]
