# Generated by Django 4.1.10 on 2023-12-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0014_testsubmission_selected_question_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsubmission",
            name="selected_question_ids",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dictionary of question IDs already selected for each section of this test submission.",
            ),
        ),
    ]
