# Generated by Django 4.1.10 on 2023-12-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0016_practicetest_practicetestresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicetestresult",
            name="practice_test",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="test_manager.practicetest",
            ),
        ),
        migrations.AlterField(
            model_name="testsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("YET_TO_START", "Yet to start"),
                    ("IN_PROGRESS", "In progress"),
                    ("COMPLETED", "Completed"),
                    ("EXPIRED", "Expired"),
                ],
                default="YET_TO_START",
                max_length=20,
            ),
        ),
    ]
