# Generated by Django 4.1.10 on 2024-01-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0017_alter_practicetestresult_practice_test_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practicetest",
            options={"ordering": ["-created_at"]},
        ),
    ]
