# Generated by Django 4.1.10 on 2024-01-10 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_manager", "0027_question_reading_comprehension_passage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0018_alter_practicetest_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnsweredQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.JSONField(default=list)),
                (
                    "course_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_manager.coursesubjects",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "course_subject")},
            },
        ),
    ]
