# Generated by Django 4.1.10 on 2023-09-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0002_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
