# Generated by Django 4.1.10 on 2023-09-21 09:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0004_rename_create_date_user_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
        migrations.AddField(
            model_name="studentmetadata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentmetadata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default=9999999999,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '9#########'. Up to 10 digits allowed.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="user_manager.role",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentmetadata",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentmetadata",
            name="subscription_type",
            field=models.CharField(default="Free", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="TempUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '9#########'. Up to 10 digits allowed.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("course", models.CharField(max_length=30)),
                ("parent_email", models.EmailField(max_length=254, unique=True)),
                (
                    "parent_phone_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '9#########'. Up to 10 digits allowed.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("parent_first_name", models.CharField(max_length=30)),
                ("parent_last_name", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_manager.role",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
