# Generated by Django 4.1.10 on 2023-09-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0005_remove_user_roles_studentmetadata_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempuser",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_manager.role",
            ),
        ),
    ]
