# Generated by Django 4.1.10 on 2023-09-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0006_alter_tempuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmetadata",
            name="subscription_end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="studentmetadata",
            name="subscription_start_date",
            field=models.DateField(null=True),
        ),
    ]
