# Generated by Django 4.1.10 on 2023-09-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0008_alter_studentmetadata_faculty_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentmetadata",
            name="subscription_end_date",
        ),
        migrations.RemoveField(
            model_name="studentmetadata",
            name="subscription_start_date",
        ),
        migrations.RemoveField(
            model_name="studentmetadata",
            name="subscription_type",
        ),
    ]
