# Generated by Django 4.1.10 on 2023-11-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0010_passwordresettoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tempuser",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["id"]},
        ),
    ]
