# Generated by Django 4.1.10 on 2023-11-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0011_alter_tempuser_options_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempuser",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="tempuser",
            name="parent_email",
        ),
        migrations.RemoveField(
            model_name="tempuser",
            name="parent_first_name",
        ),
        migrations.RemoveField(
            model_name="tempuser",
            name="parent_last_name",
        ),
        migrations.RemoveField(
            model_name="tempuser",
            name="parent_phone_number",
        ),
        migrations.RemoveField(
            model_name="tempuser",
            name="role",
        ),
    ]
