# Generated by Django 4.1.10 on 2023-11-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0012_remove_tempuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
