# Generated by Django 4.1.10 on 2023-12-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0014_remove_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tempuser",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="tempuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
