# Generated by Django 4.1.10 on 2023-12-25 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0015_rename_first_name_tempuser_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentmetadata",
            name="parent",
        ),
        migrations.AddField(
            model_name="studentmetadata",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="father_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentmetadata",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mother_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
