# Generated by Django 4.1.10 on 2023-12-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_manager",
            "0016_remove_studentmetadata_parent_studentmetadata_father_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempuser",
            name="course",
        ),
        migrations.AddField(
            model_name="tempuser",
            name="courses",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
