# Generated by Django 4.1.10 on 2024-02-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0017_remove_tempuser_course_tempuser_courses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tempuser",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
    ]
